package io.github.mksfilmoteka.media.file

import io.swagger.v3.oas.annotations.media.Schema

@Schema(description = "Response returned after a file upload")
data class UploadFileResponse(
    @field:Schema(
        description = "Stored file name generated by the media service",
        example = "b8f3d76a-8b8f-4d57-a7b8-1a74d3f2b65a.jpg",
    )
    val fileName: String,

    @field:Schema(
        description = "URL path that can be used to load the uploaded file",
        example = "/api/v1/media/files/b8f3d76a-8b8f-4d57-a7b8-1a74d3f2b65a.jpg",
    )
    val url: String,
)
