server:
  port: 8081

spring:
  application:
    name: filmoteka-media

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  level:
    io.github.mksfilmoteka.media: INFO

media:
  root-location: uploads
  image:
    max-width: 300
    max-height: 450
    output-quality: 0.9
